version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    ports:
      - "9997:9997"
    
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
    env_file:
      - ./frontend/.env
    ports:
      - "8501:8501"
    depends_on:
      - backend